/*
 * This Spock specification was auto generated by running the Gradle 'init' task
 * by 'PhuongLQ' at '6/23/16 10:48 PM' with Gradle 2.14
 *
 * @author PhuongLQ, @date 6/23/16 10:48 PM
 */

import spock.lang.Specification

class LibraryTest extends Specification{
    def "someLibraryMethod returns true"() {
        setup:
        Library lib = new Library()
        when:
        def result = lib.someLibraryMethod()
        then:
        result == true
    }
}
