/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'PhuongLQ' at '6/23/16 10:48 PM' with Gradle 2.14
 *
 * @author PhuongLQ, @date 6/23/16 10:48 PM
 */
class Library {
    boolean someLibraryMethod() {
        true
    }
}
